---

version: "3"

services:
  redis:
    restart: always
    image: redis:alpine
    volumes:
      - .data/redis:/data

  authconfig:
    build:
      context: ./authconfig
    environment:
      - DB_HOST=redis:6379
    depends_on:
      - redis

  bot:
    build:
      context: ./bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=redis:6379
      - ADMIN_ID=${ADMIN_ID}
    depends_on:
      - redis

  containerssh:
    image: containerssh/containerssh
    ports:
      - 0.0.0.0:2222:2222
    volumes:
      - type: bind
        source: ./config/config.yml
        target: /etc/containerssh/config.yaml

      - type: bind
        source: .secrets/ssh_host_rsa_key
        target: /var/secrets/ssh_host_rsa_key

      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

    user: root
    depends_on:
      - bot
      - authconfig
